# Use Node 16 LTS
FROM node:16

# Declare build args with defaults
ARG PORT=8000
# Create app directory
WORKDIR /usr/src/app
COPY package*.json ./
# Bundle app source
COPY . .
# Install npm packages
RUN npm install
# Expose desired port
EXPOSE $PORT
# Excec command
CMD npm start;
