# Use Node 16 LTS
FROM node:16

ARG ENDPOINT=127.0.0.1
ENV ENDPOINT=${ENDPOINT}
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}
# Declare build args with defaults
ARG PORT=8000
# Create app directory
WORKDIR /usr/src/app
COPY package*.json ./
# Bundle app source
COPY . .
# Install npm packages
RUN npm install
# Expose desired port
EXPOSE $PORT
# Excec command
CMD npm start;
