version: "3.8"

x-app: &default-app
  restart: on-failure
  stop_grace_period: "3s"

  healthcheck:
    interval: "60s"
    timeout: "3s"
    start_period: "5s"
    retries: 3

services:
  backend:
    <<: *default-app
    env_file:
      - ./backend/.env.prod
    container_name: backend
    image: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile.prod
    healthcheck:
      test: "http://127.0.0.1:9000/api/weather"
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/usr/src/app:rw
      - /dev/null:/usr/src/app/.env.dev
      - /dev/null:/usr/src/app/.env.prod

  frontend:
    <<: *default-app
    container_name: frontend
    image: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.prod
    healthcheck:
      test: "http://127.0.0.1/"
    ports:
      - "8000:80"
    tty: true
